---
galaxy_info:
  author: labrats.work
  description: Install and configure FluxCD for GitOps
  license: GPL-3.0-or-later
  min_ansible_version: "2.14"
  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
  galaxy_tags:
    - kubernetes
    - gitops
    - fluxcd
    - cd

dependencies: []
